project_id = "mqdjwhjtvjnktobgruuu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"

[functions.import-dnd-monsters]
verify_jwt = false

[functions.meshy-models]
verify_jwt = false

[functions.auth-google-callback]
verify_jwt = false

[functions.debug-error]
verify_jwt = true

[functions.auto-fix-error]
verify_jwt = true

[db]
port = 54322

[storage]
enabled = true
port = 54323
image_transformation = {enabled = true}

[inbucket]
enabled = true
port = 54324
